### ISSUE TITLE
Sampler subclassing the Synthesiser 

### ISSUE THREAD

**Issue by mhamilt** [RuiYang12345/Audio_Programming_final#1]
Are you sure you wan to do that?

**Comment by mhamilt** [comment]
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L14

**Comment by mhamilt** [comment]
Should probably be a sampler voice

https://docs.juce.com/master/classSamplerVoice.html

**Comment by mhamilt** [comment]
https://docs.juce.com/master/classSamplerSound.html

**Comment by RuiYang12345** [comment]
It seems I still have to inherit from Synthesiser, otherwise it does not know where the 'addSound' is:

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L38

**Comment by mhamilt** [comment]
If you look at Tom's example code you should get a good idea of what order things happen. 

Adding the sound should happen in your `PluginProcessor` using an instance of `juce::Synthesiser`


Like when you add the voice here

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L68

**Comment by mhamilt** [comment]
If you are adding code and it isn't working, pop it in a message or update the code on the git and link to it

**Comment by RuiYang12345** [comment]
I want to call the Sampler class to filter and synth class easier, so I still would like to keep the subclass like that so far

**Comment by mhamilt** [comment]
The sampler stores a single, or a series, of audio samples. In which case, the [`juce::SamplerVoice`](https://docs.juce.com/master/classSynthesiserVoice.html) seems like it would be more relevant

i.e.

```cpp
class RYSampler : public juce::SamplerVoice
{
    // check Tom's example code for how to deal with inheritance
};
```

**Comment by RuiYang12345** [comment]
> The sampler stores a single, or a series, of audio samples. In which case, the [`juce::SamplerVoice`](https://docs.juce.com/master/classSynthesiserVoice.html) seems like it would be more relevant
> 
> i.e.
> 
> ```c++
> class RYSampler : public juce::SamplerVoice
> {
>     // check Tom's example code for how to deal with inheritance
> };
> ```

I try this and I got an error like this:
<img width="1127" alt="Screenshot 2022-05-10 at 10 37 41" src="https://user-images.githubusercontent.com/78182424/167598881-8f5b24d2-2792-438d-be64-169a37641175.png">

**Comment by mhamilt** [comment]
sampler shouldn't be a `RySampler`, rather it should be a `juce::Synthesiser`

**Comment by mhamilt** [comment]
See here 

https://github.com/RuiYang12345/Audio_Programming_final/issues/7#issuecomment-1122066828

**Comment by RuiYang12345** [comment]
Do I need to rename the "setSample" class?

<img width="1133" alt="Screenshot 2022-05-10 at 11 06 51" src="https://user-images.githubusercontent.com/78182424/167604742-49709be6-f39a-4699-8538-cc0f1f8dce82.png">

**Comment by mhamilt** [comment]
You set the sample in the constructor of [`SynthesiserSound`](https://docs.juce.com/master/classSamplerSound.html#ad26e044243f4802000b8dcbb6dd15cee), not in the synthesiser itself.

Rather than splitting your efforts. I'd focus on getting the [`DreamyVoiceSynth`](https://github.com/RuiYang12345/Audio_Programming_final/issues/5) working and come back to this one.

**Comment by RuiYang12345** [comment]
okay thanks, it seems I need to add extra oscillator elements for the synth right? because previously I was thinking about adding voice from binary data, to the synth class which is throublesome.

**Comment by mhamilt** [comment]
You can’t add oscillators to the _Voice_ which then get added to the `synth`

you wouldn’t directly add oscillators to the synth

neither by subclassing nor directly

**Comment by mhamilt** [comment]
I'm afraid you'll need to elaborate on that as I don't quite follow

> yeah I have the oscillator subclass file, what I mean is the synth class is currently only work for strings data in oscillator class? ranther than binary data.

**Comment by RuiYang12345** [comment]
> > yeah I have the oscillator subclass file, what I mean is the synth class is currently only work for strings data in oscillator class? ranther than binary data.
> 
> I'm afraid you'll need to elaborate on that as I don't quite follow

ideally I want to set up the synth class for the voice with the audio file, which comes from sampler, so that I can twist the wav.file with adsr parameters. but the synth class is for oscillator only, so I put oscillator into the synth instead of sampler(the wav. file).

**Comment by mhamilt** [comment]
You might need to update the code on the git for this to be more clear

**Comment by RuiYang12345** [comment]
I did not write the code in git hub desktop. Do I need to create new repository or cover the original one with update code?

**Comment by mhamilt** [comment]
It should be just a case of adding your new `Source` folder to your `~/Documents/GitHub/[Audio_Programming_final` folder then commit and push in the desktop app

**Comment by RuiYang12345** [comment]
originally it was a sampler, the object from RYsampler, now I use oscillators here:
https://github.com/RuiYang12345/Audio_Programming_final/blob/adfa8723c2b5f4f0ad7464c0339be0de5cd528c9/Source/DreamyVoiceSynth.h#L187

**Comment by mhamilt** [comment]
Then this issue is closed and we should start a new one covering the current problem
