### ISSUE TITLE
casting voices to your Filter class

### ISSUE THREAD

**Issue by mhamilt** [RuiYang12345/Audio_Programming_final#2]
This is not going be a good idea in the current format

**Comment by mhamilt** [comment]
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L81-L85

**Comment by mhamilt** [comment]
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/Filter.h#L11

**Comment by mhamilt** [comment]
https://docs.juce.com/master/classSynthesiserVoice.html

**Comment by RuiYang12345** [comment]
so do I need to keep that?

**Comment by mhamilt** [comment]
> so do I need to keep that?

I think you need to make a decision on which class is going to be doing the processing on each voice, then turn that into something that subclasses from `juce::SynthesiserVoice`

**Comment by RuiYang12345** [comment]
RYsampler is the class for filtering. Bur once I change the subclass to juce::SynthesiserVoice, 'add sound'function does not work, which goes back to the first issue.

**Comment by mhamilt** [comment]
`Filter` would need to inherit `juce::SynthesiserVoice` in order for this to work.

i.e.

```cpp
class Filter : juce::SynthesiserVoice
```

However, `Filter` currently doesn't contain all the functions required for this to work. I strongly suggest going back and watching Tom's lecture and flagging up anything in it that doesn't make sense. Then we can decontextualise those problems to your own project

**Comment by mhamilt** [comment]
From what you have described, I think it's probably best just to filter the output of the synth

in pseudocode

```cpp

synth.renderNextBlock(buffer, midiMessages, 0, buffer.getNumSamples());

for (int i=0; i<numSamples; i++)
{
  left[i]  = leftFilter.processSingleSampleRaw(left[i]);
  right[i] = rightFilter.processSingleSampleRaw(right[i]);
}
```
