### ISSUE TITLE
Voices never added to Synth

### ISSUE THREAD

**Issue by mhamilt** [RuiYang12345/Audio_Programming_final#5]

**Comment by mhamilt** [comment]
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L87-L92

**Comment by mhamilt** [comment]
Is there a reason you can't add voice the same way as here?

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L65-L74

**Comment by RuiYang12345** [comment]
I would like to use adsr params for the audio files of the sampler. I have spent all night to get sound for the synth but it still does not work. It seems I need to change the start note and render next block of the synth class because it runs a different way in the sampler voice. And I'm trying to change it rather than inherit it but I do not know how. Could anybody point me to how to solve this?

**Comment by mhamilt** [comment]
You are trying to get voices from this synthesiser object

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.h#L74

At some point in your constructor you'll need to


```cpp
    //voice count
    for (int i=0; i<voiceCount; i++)
    {
        synth.addVoice( new DreamyVoiceSynth() );
    }

    synth.addSound( /*ERROR: YOU HAVE NOT DECLARED ANY SythesiserSound CLASS*/ );
    
```

**Comment by RuiYang12345** [comment]
> You are trying to get voices from this synthesiser object
> 
> https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.h#L74
> 
> At some point in your constructor you'll need to
> 
> ```c++
>     //voice count
>     for (int i=0; i<voiceCount; i++)
>     {
>         synth.addVoice( new DreamyVoiceSynth() );
>     }
> 
>     synth.addSound( /*ERROR: YOU HAVE NOT DECLARED ANY SythesiserSound CLASS*/ );
>     
> ```

I am not sure what SythesiserSound CLASS I should declare here, should I move the samplerSound to here:

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L38

**Comment by mhamilt** [comment]
>I am not sure what `SythesiserSound` CLASS I should declare here, should I move the samplerSound to here:

So this comes from Tom's example code. You would have some kind of `SythesiserSound` class like

```cpp
// SOUND
class DreamyVoiceSynthSound : public juce::SynthesiserSound
{
public:
    bool appliesToNote      (int) override      { return true; }
    //--------------------------------------------------------------------------
    bool appliesToChannel   (int) override      { return true; }
};
```

Here is the example Tom has put on Learn

[YourSynthesiser.txt](https://github.com/RuiYang12345/Audio_Programming_final/files/8660485/YourSynthesiser.txt)

**Comment by RuiYang12345** [comment]
> > I am not sure what `SythesiserSound` CLASS I should declare here, should I move the samplerSound to here:
> 
> So this comes from Tom's example code. You would have some kind of `SythesiserSound` class like
> 
> ```c++
> // SOUND
> class DreamyVoiceSynthSound : public juce::SynthesiserSound
> {
> public:
>     bool appliesToNote      (int) override      { return true; }
>     //--------------------------------------------------------------------------
>     bool appliesToChannel   (int) override      { return true; }
> };
> ```
> 
> Here is the example Tom has put on Learn
> 
> [YourSynthesiser.txt](https://github.com/RuiYang12345/Audio_Programming_final/files/8660485/YourSynthesiser.txt)

This only work for oscillator instead of binary data from audio files right? I got the two mixed up.

**Comment by mhamilt** [comment]
That is correct. This is for audio you are generating, not audio that comes from a sampler.

for samplers you can us the corresponding SamplerSound and SamplerVoice classes

**Comment by RuiYang12345** [comment]
> That is correct. This is for audio you are generating, not audio that comes from a sampler.
> 
> for samplers you can us the corresponding SamplerSound and SamplerVoice classes

I see, sorry for mixed up. The audio I mean previously is the audio comes from a sampler, if it is oscialltor I know how to do that, thank you Matthew.
