### ISSUE TITLE
dereferencing your parameters every sample

### ISSUE THREAD

**Issue by mhamilt** [RuiYang12345/Audio_Programming_final#6]
A bit inefficient, do it once per buffer

**Comment by mhamilt** [comment]
E.g. the `gainParam` here

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L154-L155


the LFO params here

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L144-L145

The filter parameters here
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L137

**Comment by RuiYang12345** [comment]
are there anyways to dereference all of the buffers together?

**Comment by mhamilt** [comment]
Rather than doing it inside this

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L131

Get them outside after this block

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L116-L129


i.e.

```cpp
    juce::ScopedNoDenormals noDenormals;
    
    sampler.renderNextBlock(buffer, midiMessages, 0, buffer.getNumSamples());
    
    int numSamples = buffer.getNumSamples();
    
    //pointers to audio arrays
    float* left = buffer.getWritePointer(0);
    float* right = buffer.getWritePointer(1);
    
    float bufferGain = *gainParam;
    float lfo1Rate = *lfoRate01Param;
    float lfo2Rate = *lfoRate02Param;

    float freq = *lowpassParam + (*highpassParam - *lowpassParam);
    //DSP LOOP
    for (int i=0; i<numSamples; i++)
```

**Comment by RuiYang12345** [comment]
Got it thanks a lot!
