### ISSUE TITLE
Remove unused or placeholder elements

### ISSUE THREAD

**Issue by mhamilt** [RuiYang12345/Audio_Programming_final#7]

**Comment by RuiYang12345** [comment]
could you point out which elements apart from 'set sampleRate' and 'set frequency', please?

**Comment by mhamilt** [comment]
Things like this are generally going to clutter your view.

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L158-L159

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L134

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L81-L85

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/Filter.h#L28-L29

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/Filter.h#L17

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginEditor.cpp#L17

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L41-L44

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L38

**Comment by RuiYang12345** [comment]
I am still confused about how to set up filter parameters without initialising it.

[Audio_Programming_final/Source/Filter.h](https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/Filter.h#L28-L29)

[Audio_Programming_final/Source/Filter.h](https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/Filter.h#L17)

**Comment by RuiYang12345** [comment]
Where can I get sampleRate of the sampler? It should be the same as the synth right but how to avoid double setting? I am a bit lost here.
[Audio_Programming_final/Source/Filter.h](https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/Filter.h#L17)

**Comment by mhamilt** [comment]
> I think this is essential for the scaling of sampler sound? Are there any other ways to replace it then?
> [Audio_Programming_final/Source/RYSampler.h](https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L38)

See #5 


You should add the Sound in here

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L63-L73

I think you want this

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.h#L65

to be


```cpp
    juce::Synthesiser sampler;
```

and this

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L63-L73


to be


```cpp
    //===========================================================


    //voice count
    for (int i=0; i<voiceCount; i++)
    {
        sampler.addVoice( new juce::SamplerVoice() );
    }
   
 auto* reader = formatManager.createReaderFor(std::make_unique<juce::MemoryInputStream> (sourceData,sourceDataSize, false));
        
      // Scaling the range from C2-C7 (36 - 96)
      juce::BigInteger midiNotes;
      midiNotes.setRange(36,60,true);

     sampler.addSound(new juce::SamplerSound("Ding", *reader, midiNotes, 60, 0, 0.1, 10.0 ));
    
```

**Comment by RuiYang12345** [comment]
And I got errors like this:
<img width="1136" alt="Screenshot 2022-05-10 at 11 00 33" src="https://user-images.githubusercontent.com/78182424/167603534-158ce8c1-43bc-447d-bc02-efdb3db41436.png">

so I need to identify those elements in the Plugin processor header file?

**Comment by mhamilt** [comment]
Apologies, that was just a rough template of where things would go.

You still need to fill in the blanks with your variables

- `formatManager`
- `sourceData`
- `sourceDataSize`

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L53
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L24
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L29

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L72
https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L27


e.g.

```cpp
for (int i=0; i<voiceCount; i++)
{
  sampler.addVoice( new juce::SamplerVoice() );
}
juce::AudioFormatManager formatManager;
formatManager.registerBasicFormats();

auto* reader = formatManager.createReaderFor(std::make_unique<juce::MemoryInputStream> 
  (BinaryData::RY_Metal_Knock_C4_wav,
  BinaryData::RY_Metal_Knock_C4_wavSize, 
  false));

// Scaling the range from C2-C7 (36 - 96)
juce::BigInteger midiNotes;
midiNotes.setRange(36,60,true);

sampler.addSound(new juce::SamplerSound("Ding", *reader, midiNotes, 60, 0, 0.1, 10.0 ));
```

**Comment by RuiYang12345** [comment]
> Apologies, that was just a rough template of where things would go.
> 
> You still need to fill in the blanks with your variables
> 
> * `formatManager`
> * `sourceData`
> * `sourceDataSize`
> 
> https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L53
> 
> 
> https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L24
> 
> 
> https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L29
> 
> https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/PluginProcessor.cpp#L72
> 
> 
> https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L27
> 
> e.g.
> 
> ```c++
> for (int i=0; i<voiceCount; i++)
> {
>   sampler.addVoice( new juce::SamplerVoice() );
> }
> juce::AudioFormatManager formatManager;
> formatManager.registerBasicFormats();
> 
> auto* reader = formatManager.createReaderFor(std::make_unique<juce::MemoryInputStream> 
>   (BinaryData::RY_Metal_Knock_C4_wav,
>   BinaryData::RY_Metal_Knock_C4_wavSize, 
>   false));
> 
> // Scaling the range from C2-C7 (36 - 96)
> juce::BigInteger midiNotes;
> midiNotes.setRange(36,60,true);
> 
> sampler.addSound(new juce::SamplerSound("Ding", *reader, midiNotes, 60, 0, 0.1, 10.0 ));
> ```

Thanks but I am not sure why should I move that. The sampler can get the sound in the subclass. The main problem is whether I can use the filter class for the audio comes from the sampler now. If not I would consider removing the sampler subclass #1 and putting it in the processor folder directly.

**Comment by mhamilt** [comment]
There is nothing wrong with subclassing it as you have, it is maybe a little intuitive and it means you'll have to tweak the workflow as laid out in the JUCE tutorials.

You're also adding some methods to your sampler class that might not be a good idea such as

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L46-L49

and

https://github.com/RuiYang12345/Audio_Programming_final/blob/1fcda81768e974379f3ac7a5e01fce090643c48d/Source/RYSampler.h#L21-L25

as this is kind od functionality that is covered by the `juce::Synthesiser`

**Comment by RuiYang12345** [comment]
I separate the class, would like the Filter class to get RySampler data, do I do it in the opposite way then?
